server:
  port: 8085

spring:
  application:
    name: grade-system-server
  datasource:
    url: jdbc:postgresql://113.45.211.133:8000/db_zjut?useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: db_user34
    password: xxxxxx
# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.jh.forum.start
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn